### ISSUE TITLE
How long does MPLT take to train

### ISSUE THREAD

**Issue by Eric-Chen-L** [HusterYoung/MPLT#1]
Hello, I am currently experiencing the following issue when trying to reproduce your code with 2 cards: only 1 card has a normal GPU-Util, while the other card has an abnormal GPU-Util, and only 4 epochs have been run in 14 hours. May I ask how long it takes for you to run MPLT normally?
你好，我目前尝试2卡复现您的代码时发生下面的问题：出现只有1张卡GPU-Utile正常，另外一张卡GPU-Utile异常，且14小时只跑了4个epoch。请问您正常跑完一次MPLT是多长时间？

**Comment by HusterYoung** [comment]
您好，我使用2张3090训练15个epoch不到10个小时就能完成，我不是很确定您说的卡2异常具体是什么问题。













--

Luo Yang
Beijing，China




在 2023-10-18 09:23:49，"Chen Liang" ***@***.***> 写道：

Hello, I am currently experiencing the following issue when trying to reproduce your code with 2 cards: only 1 card has a normal GPU-Util, while the other card has an abnormal GPU-Util, and only 4 epochs have been run in 14 hours. May I ask how long it takes for you to run MPLT normally?
你好，我目前尝试2卡复现您的代码时发生下面的问题：出现只有1张卡GPU-Utile正常，另外一张卡GPU-Utile异常，且14小时只跑了4个epoch。请问您正常跑完一次MPLT是多长时间？

**Comment by Eric-Chen-L** [comment]
https://github.com/HusterYoung/MPLT/blob/b6e06d8300853c165232102dedf7edd527543c3f/lib/models/mplt_track/vit_mplt_care.py#L34C1-L34C1

感谢回复，异常发生在这个多余引用中，已经解决，但发生一个奇怪的情况，我没有修改任何数据和代码，pretrain采用的是OSTrack 256 300epoch训练，训练loss和IOU以及结果都不正常，请问是有啥没注意到的吗

![image](https://github.com/HusterYoung/MPLT/assets/61507255/50d5fe2d-513d-4488-939a-5d21cf75281d)
![image](https://github.com/HusterYoung/MPLT/assets/61507255/7b7d636c-e6db-4ff2-a0d0-22b8ed9893a4)

**Comment by HusterYoung** [comment]
> https://github.com/HusterYoung/MPLT/blob/b6e06d8300853c165232102dedf7edd527543c3f/lib/models/mplt_track/vit_mplt_care.py#L34C1-L34C1
> 
> 感谢回复，异常发生在这个多余引用中，已经解决，但发生一个奇怪的情况，我没有修改任何数据和代码，pretrain采用的是OSTrack 256 300epoch训练，训练loss和IOU以及结果都不正常，请问是有啥没注意到的吗
> 
> ![image](https://user-images.githubusercontent.com/61507255/276632342-50d5fe2d-513d-4488-939a-5d21cf75281d.png) ![image](https://user-images.githubusercontent.com/61507255/276632378-7b7d636c-e6db-4ff2-a0d0-22b8ed9893a4.png)

直接test的结果正常吗？如果正常那就不是权重文件的问题。其次检查一下是否有某些层被冻结了参数？
