### ISSUE TITLE
论文复现问题

### ISSUE THREAD

**Issue by MelanTech** [HusterYoung/MPLT#2]
您好，我在尝试复现您的工作时发现在LasHeR数据集上的测试指标与论文中差异较大（PR -1.6% / SR -0.6%），请问您在训练时使用的是**LasHeR0327**还是**LasHeR0428**，这是否与数据集版本或环境有关？此外，不知道您是否方便提供一下训练日志以便对比，感激不尽！

**环境：**
torch 1.11.0 + CUDA11.4
LasHeR 0327
RTX3090 * 2

**Comment by Eric-Chen-L** [comment]
您好，我想问问你在复现效果时是否对这份代码有所修改，因为我在未进行任何修改时训练拟合非常糟糕，全部层都未冻结，pretrain也是用作者给的参数，但正常跟踪没跑出来，感觉非常困惑，想问问您的情况，好奇问一下您说LasHeR0327和LasHeR0428是指什么，是指LasHeR在这两个时间的发布的版本吗

**Comment by MelanTech** [comment]
> 您好，我想问问你在复现效果时是否对这份代码有所修改，因为我在未进行任何修改时训练拟合非常糟糕，全部层都未冻结，pretrain也是用作者给的参数，但正常跟踪没跑出来，感觉非常困惑，想问问您的情况，好奇问一下您说LasHeR0327和LasHeR0428是指什么，是指LasHeR在这两个时间的发布的版本吗

您好，我没有对代码进行任何改动，在更换环境（数据集仍然使用LasHeR0327）以后性能有所提升，但是还是和论文中有一点差距（PR -0.98% / SR -0.1%）。关于数据集，LasHeR0327和LasHeR0428是指LasHeR发布的两个版本，LasHeR0428应该是作者发现一些问题修改后上传的新版本数据集。LasHeR两个版本的数据集都存在图片空白的情况，在官方GitHub的Issue上有讨论，对于空白的图片我采用了删除的操作，您可以检查一下这一点。此外，您也可以检查一下您的环境配置是否符合官方提供的版本要求。希望可以帮到您。

**Comment by HusterYoung** [comment]
> 您好，我在尝试复现您的工作时发现在LasHeR数据集上的测试指标与论文中差异较大（PR -1.6% / SR -0.6%），请问您在训练时使用的是**LasHeR0327**还是**LasHeR0428**，这是否与数据集版本或环境有关？此外，不知道您是否方便提供一下训练日志以便对比，感激不尽！
> 
> **环境：** torch 1.11.0 + CUDA11.4 LasHeR 0327 RTX3090 * 2

您好，我使用的是0428版本的LasHeR，有一些损坏的图片是直接剔除了

**Comment by HusterYoung** [comment]
关于训练log，最近重装系统被我弄丢了……我看看这两天能不能重新训一版出来吧

**Comment by Eric-Chen-L** [comment]
> > 您好，我想问问你在复现效果时是否对这份代码有所修改，因为我在未进行任何修改时训练拟合非常糟糕，全部层都未冻结，pretrain也是用作者给的参数，但正常跟踪没跑出来，感觉非常困惑，想问问您的情况，好奇问一下您说LasHeR0327和LasHeR0428是指什么，是指LasHeR在这两个时间的发布的版本吗
> 
> 您好，我没有对代码进行任何改动，在更换环境（数据集仍然使用LasHeR0327）以后性能有所提升，但是还是和论文中有一点差距（PR -0.98% / SR -0.1%）。关于数据集，LasHeR0327和LasHeR0428是指LasHeR发布的两个版本，LasHeR0428应该是作者发现一些问题修改后上传的新版本数据集。LasHeR两个版本的数据集都存在图片空白的情况，在官方GitHub的Issue上有讨论，对于空白的图片我采用了删除的操作，您可以检查一下这一点。此外，您也可以检查一下您的环境配置是否符合官方提供的版本要求。希望可以帮到您。

感谢感谢，LasHeR这块没了解过，我去了解一下

**Comment by MelanTech** [comment]
> 关于训练log，最近重装系统被我弄丢了……我看看这两天能不能重新训一版出来吧

感谢您的帮助！

**Comment by HusterYoung** [comment]
> > 关于训练log，最近重装系统被我弄丢了……我看看这两天能不能重新训一版出来吧
> 
> 感谢您的帮助！

log已上传，复现结果无误。

**Comment by MelanTech** [comment]
> > > 关于训练log，最近重装系统被我弄丢了……我看看这两天能不能重新训一版出来吧
> > 
> > 
> > 感谢您的帮助！
> 
> log已上传，复现结果无误。

非常感谢！

**Comment by shijiahahaha** [comment]
您好，请问有0327到0428版本的补丁吗？并且我还想要一下论文里pr=72.0这个版本的权重文件，shiyuzsy@126.com 这是我的邮箱，感谢

**Comment by MelanTech** [comment]
> 您好，请问有0327到0428版本的补丁吗？并且我还想要一下论文里pr=72.0这个版本的权重文件，[shiyuzsy@126.com](mailto:shiyuzsy@126.com) 这是我的邮箱，感谢

您好，据我所知，LasHeR官方并没有提供0327到0428版本的补丁，而且我发现目前官方提供的LasHeR0428版本的下载链接已经失效，您或许可以联系@BUGPLEASEOUT获取
另外，您需要的权重文件可以在以下链接获取：
https://pan.baidu.com/s/1wxnEor8ksO2g3r_eBPPl6A?pwd=ce0b

**Comment by shijiahahaha** [comment]
感谢您的回复，目前确实在复现结果的时候遇到了些困难，lasher/test/1stcol4thboy/infrared中有很多空白的图片，请问类似这种的您是去除了还是保留了？



在 2024-10-11 09:21:40，"MelanTech" ***@***.***> 写道：

***@***.*** 这是我的邮箱，感谢

***@***.***获取
另外，您需要的权重文件可以在以下链接获取：
https://pan.baidu.com/s/1wxnEor8ksO2g3r_eBPPl6A?pwd=ce0b

**Comment by MelanTech** [comment]
> 感谢您的回复，目前确实在复现结果的时候遇到了些困难，lasher/test/1stcol4thboy/infrared中有很多空白的图片，请问类似这种的您是去除了还是保留了？ 在 2024-10-11 09:21:40，"MelanTech" ***@***.***> 写道： ***@***.*** 这是我的邮箱，感谢 ***@***.***获取 另外，您需要的权重文件可以在以下链接获取： https://pan.baidu.com/s/1wxnEor8ksO2g3r_eBPPl6A?pwd=ce0b — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我们并未修改或删除任何测试集中的数据，而是仅剔除了训练集中损坏的图片

**Comment by shijiahahaha** [comment]
好滴，感谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月12日 14:38 |
| 收件人 | HusterYoung/MPLT ***@***.***> |
| 抄送人 | shijiahahaha ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [HusterYoung/MPLT] 论文复现问题 (Issue #2) |

感谢您的回复，目前确实在复现结果的时候遇到了些困难，lasher/test/1stcol4thboy/infrared中有很多空白的图片，请问类似这种的您是去除了还是保留了？ 在 2024-10-11 09:21:40，"MelanTech" @.> 写道： @. 这是我的邮箱，感谢 @.获取 另外，您需要的权重文件可以在以下链接获取： https://pan.baidu.com/s/1wxnEor8ksO2g3r_eBPPl6A?pwd=ce0b — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

我们并未修改或删除任何测试集中的数据，而是仅剔除了训练集中损坏的图片

**Comment by shijiahahaha** [comment]
> 这一点。此外，您也可以检查一下您的环境配置是否符合官方提供的版本要求。希望可以帮到您。

请问测试集中有一些空白图片您有删除吗还是只对训练集做了修改
