### ISSUE TITLE
模型速度与参数量问题

### ISSUE THREAD

**Issue by MelanTech** [HusterYoung/MPLT#3]
您好，我在尝试复现您的工作时发现模型的运行速度与论文中的速度有很大出入，请问您是怎么对模型进行速度和参数量测试的？

我修改了tracking下profile_model.py进行了模型速度测试，测试结果如下图：
![image](https://github.com/HusterYoung/MPLT/assets/31992884/0d1a030a-f93f-4b7a-a2eb-624fac92657c)
测试的速度和参数量都与论文中有很大差异

下面是我修改的测试脚本代码：
[profile_model.zip](https://github.com/HusterYoung/MPLT/files/13456463/profile_model.zip)

测试环境：
torch 1.11.0 + CUDA11.4
NVIDIA A40 * 1 以及 NVIDIA Geforce 3090 * 1

**Comment by HusterYoung** [comment]
您好，感谢您的问题。我重新检查了参数量计算的部分，我想我在论文中应该是忘记标注参数量是指单模态分支的参数量了，我会对其进行修改。我使用的计算工具是FlopCountAnalysis，代码的位置在 “MPLT/lib/models/mplt_track/vit_mplt_care.py” 第661-667行。此外，关于参数量计算结果我也附上了，供您参考。
[parameters count.txt](https://github.com/HusterYoung/MPLT/files/13462960/parameters.count.txt)

**Comment by HusterYoung** [comment]
关于FPS的问题，我使用的是OSTrack中自带的FPS估计，代码位于“/MPLT/lib/test/evaluation/running.py“第145-150行，另外，带FPS计算输出的results文件也附上，供您分析。
[lasher-time.zip](https://github.com/HusterYoung/MPLT/files/13462967/lasher-time.zip)

**Comment by HusterYoung** [comment]
补充：以上结果测试环境同readme file，使用单张RTX3090显卡，test threads设置为1。

**Comment by MelanTech** [comment]
> 关于FPS的问题，我使用的是OSTrack中自带的FPS估计，代码位于“/MPLT/lib/test/evaluation/running.py“第145-150行，另外，带FPS计算输出的results文件也附上，供您分析。 [lasher-time.zip](https://github.com/HusterYoung/MPLT/files/13462967/lasher-time.zip)

您好，我按照您的方法在单张RTX3090下使用tracking下的test.py进行了模型评估，脚本参数为：
python test.py mplt_track vitb_256_mplt_32x1_1e4_lasher_15ep_sot --dataset_name lasher_test --threads 1 --num_gpus 1

但仍然无法达到您给出的results文件中的速度，我的评估结果显示每帧延迟均在0.12s左右，以下是10runone序列的部分评估结果：
![image](https://github.com/HusterYoung/MPLT/assets/31992884/8373a2e4-1121-41a4-8bd7-16310d54ad0f)

请问我使用的方法是否正确，您是否使用了其他方法进行评估？

**Comment by HusterYoung** [comment]
> > 关于FPS的问题，我使用的是OSTrack中自带的FPS估计，代码位于“/MPLT/lib/test/evaluation/running.py“第145-150行，另外，带FPS计算输出的results文件也附上，供您分析。 [lasher-time.zip](https://github.com/HusterYoung/MPLT/files/13462967/lasher-time.zip)
> 
> 您好，我按照您的方法在单张RTX3090下使用tracking下的test.py进行了模型评估，脚本参数为： python test.py mplt_track vitb_256_mplt_32x1_1e4_lasher_15ep_sot --dataset_name lasher_test --threads 1 --num_gpus 1
> 
> 但仍然无法达到您给出的results文件中的速度，我的评估结果显示每帧延迟均在0.12s左右，以下是10runone序列的部分评估结果： ![image](https://private-user-images.githubusercontent.com/31992884/285566689-8373a2e4-1121-41a4-8bd7-16310d54ad0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTEwMTgsIm5iZiI6MTcwMDg5MDcxOCwicGF0aCI6Ii8zMTk5Mjg4NC8yODU1NjY2ODktODM3M2EyZTQtMTEyMS00MWE0LThiZDctMTYzMTBkNTRhZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA1MzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMGZmYWMyYzY5ZmU1NGViMjgxMzViNTg5ODY4ZDhiOTY2NjgwYTZiNGM4OWRmYzI5MjU1YmI3MTQ4Yjg1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.833mC3kcVVUaSQfJzSldIYZe17q4IRXVef_BXCgtAW4)
> 
> 请问我使用的方法是否正确，您是否使用了其他方法进行评估？

我和您使用一模一样的脚本和参数，但想不明白为何您速度上不来，或许和CPU和硬盘有关么？

**Comment by MelanTech** [comment]
> > > 关于FPS的问题，我使用的是OSTrack中自带的FPS估计，代码位于“/MPLT/lib/test/evaluation/running.py“第145-150行，另外，带FPS计算输出的results文件也附上，供您分析。 [lasher-time.zip](https://github.com/HusterYoung/MPLT/files/13462967/lasher-time.zip)
> > 
> > 
> > 您好，我按照您的方法在单张RTX3090下使用tracking下的test.py进行了模型评估，脚本参数为： python test.py mplt_track vitb_256_mplt_32x1_1e4_lasher_15ep_sot --dataset_name lasher_test --threads 1 --num_gpus 1
> > 但仍然无法达到您给出的results文件中的速度，我的评估结果显示每帧延迟均在0.12s左右，以下是10runone序列的部分评估结果： ![image](https://private-user-images.githubusercontent.com/31992884/285566689-8373a2e4-1121-41a4-8bd7-16310d54ad0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTEwMTgsIm5iZiI6MTcwMDg5MDcxOCwicGF0aCI6Ii8zMTk5Mjg4NC8yODU1NjY2ODktODM3M2EyZTQtMTEyMS00MWE0LThiZDctMTYzMTBkNTRhZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA1MzgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMGZmYWMyYzY5ZmU1NGViMjgxMzViNTg5ODY4ZDhiOTY2NjgwYTZiNGM4OWRmYzI5MjU1YmI3MTQ4Yjg1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.833mC3kcVVUaSQfJzSldIYZe17q4IRXVef_BXCgtAW4)
> > 请问我使用的方法是否正确，您是否使用了其他方法进行评估？
> 
> 我和您使用一模一样的脚本和参数，但想不明白为何您速度上不来，或许和CPU和硬盘有关么？

也许是因为这个原因，感谢您的及时回复和帮助！

**Comment by AZong76** [comment]
![image](https://github.com/HusterYoung/MPLT/assets/103876646/0ac20778-72b3-4532-b7cc-b74b5d5c438e)


我也是0.12  0.13左右

**Comment by AZong76** [comment]
想问下您硬盘和cpu分别是什么型号呢？

**Comment by HusterYoung** [comment]
> 想问下您硬盘和cpu分别是什么型号呢？

三星970EVO+Intel Core i7 12700K

**Comment by HusterYoung** [comment]
> 想问下您硬盘和cpu分别是什么型号呢？

您也是在单张RTX3090上测试吗？

**Comment by AZong76** [comment]
> > 想问下您硬盘和cpu分别是什么型号呢？
> 
> 您也是在单张RTX3090上测试吗？

是的 单卡3090
![image](https://github.com/HusterYoung/MPLT/assets/103876646/48f7b36a-efdd-4075-a6df-53d37988cb54)

**Comment by AZong76** [comment]
> > 想问下您硬盘和cpu分别是什么型号呢？
> 
> 三星970EVO+Intel Core i7 12700K

好的好的 谢谢

**Comment by HusterYoung** [comment]
> > > 想问下您硬盘和cpu分别是什么型号呢？
> > 
> > 
> > 您也是在单张RTX3090上测试吗？
> 
> 是的 单卡3090 ![image](https://private-user-images.githubusercontent.com/103876646/290982878-48f7b36a-efdd-4075-a6df-53d37988cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc3MDEsIm5iZiI6MTcwMjcxNzQwMSwicGF0aCI6Ii8xMDM4NzY2NDYvMjkwOTgyODc4LTQ4ZjdiMzZhLWVmZGQtNDA3NS1hNmRmLTUzZDM3OTg4Y2I1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwOTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGZiMmJlZGYzZjBlZGQ4MTdkMTcwYmQ4NTU4Yjk2MTY5MzQ2ZGE5MGYzZGVhNDM1NGZmZDc0MjY2ZDY4NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E0yjlb8MWnPU7qMQyke7QiuLWibZLh5XgkpTq1Fap5o)

thread改成1了吗？

**Comment by AZong76** [comment]
> > > > 想问下您硬盘和cpu分别是什么型号呢？
> > > 
> > > 
> > > 您也是在单张RTX3090上测试吗？
> > 
> > 
> > 是的 单卡3090 ![image](https://private-user-images.githubusercontent.com/103876646/290982878-48f7b36a-efdd-4075-a6df-53d37988cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc3MDEsIm5iZiI6MTcwMjcxNzQwMSwicGF0aCI6Ii8xMDM4NzY2NDYvMjkwOTgyODc4LTQ4ZjdiMzZhLWVmZGQtNDA3NS1hNmRmLTUzZDM3OTg4Y2I1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwOTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGZiMmJlZGYzZjBlZGQ4MTdkMTcwYmQ4NTU4Yjk2MTY5MzQ2ZGE5MGYzZGVhNDM1NGZmZDc0MjY2ZDY4NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E0yjlb8MWnPU7qMQyke7QiuLWibZLh5XgkpTq1Fap5o)
> 
> thread改成1了吗？

是的，这是thread=1正在跑test的状态，但我的实验项目是在机械硬盘中进行的，也许是这个原因。

**Comment by HusterYoung** [comment]
> > > > > 想问下您硬盘和cpu分别是什么型号呢？
> > > > 
> > > > 
> > > > 您也是在单张RTX3090上测试吗？
> > > 
> > > 
> > > 是的 单卡3090 ![image](https://private-user-images.githubusercontent.com/103876646/290982878-48f7b36a-efdd-4075-a6df-53d37988cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc3MDEsIm5iZiI6MTcwMjcxNzQwMSwicGF0aCI6Ii8xMDM4NzY2NDYvMjkwOTgyODc4LTQ4ZjdiMzZhLWVmZGQtNDA3NS1hNmRmLTUzZDM3OTg4Y2I1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwOTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGZiMmJlZGYzZjBlZGQ4MTdkMTcwYmQ4NTU4Yjk2MTY5MzQ2ZGE5MGYzZGVhNDM1NGZmZDc0MjY2ZDY4NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E0yjlb8MWnPU7qMQyke7QiuLWibZLh5XgkpTq1Fap5o)
> > 
> > 
> > thread改成1了吗？
> 
> 是的，这是thread=1正在跑test的状态，但我的实验项目是在机械硬盘中进行的，也许是这个原因。

噢噢，那大概率是的

**Comment by AZong76** [comment]
> > > > > > 想问下您硬盘和cpu分别是什么型号呢？
> > > > > 
> > > > > 
> > > > > 您也是在单张RTX3090上测试吗？
> > > > 
> > > > 
> > > > 是的 单卡3090 ![image](https://private-user-images.githubusercontent.com/103876646/290982878-48f7b36a-efdd-4075-a6df-53d37988cb54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTc3MDEsIm5iZiI6MTcwMjcxNzQwMSwicGF0aCI6Ii8xMDM4NzY2NDYvMjkwOTgyODc4LTQ4ZjdiMzZhLWVmZGQtNDA3NS1hNmRmLTUzZDM3OTg4Y2I1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwOTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGZiMmJlZGYzZjBlZGQ4MTdkMTcwYmQ4NTU4Yjk2MTY5MzQ2ZGE5MGYzZGVhNDM1NGZmZDc0MjY2ZDY4NDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E0yjlb8MWnPU7qMQyke7QiuLWibZLh5XgkpTq1Fap5o)
> > > 
> > > 
> > > thread改成1了吗？
> > 
> > 
> > 是的，这是thread=1正在跑test的状态，但我的实验项目是在机械硬盘中进行的，也许是这个原因。
> 
> 噢噢，那大概率是的

感谢您耐心的回复🤝🤝🤝
