### ISSUE TITLE
How to test？

### ISSUE THREAD

**Issue by AZong76** [HusterYoung/MPLT#4]
Hello, I tried to recurrent your model and encountered a problem during model testing.
Executing: 
python track/test.py mplt_track vitb_256_mplt_32x1_1e4_lasher_15ep_sot --dataset_name lasher_test --threads 6 --num_gpus 1

At this point, I have a question. 
This test code does not point to a specific training model weight. So，how can I set a specific test to a certain model weight?

Looking forward to your reply! !

**Comment by HusterYoung** [comment]
看到您在另一个问题回复了，现在已经可以正常test了是吗？

**Comment by AZong76** [comment]
嗯嗯嗯 ok了的
